import{a as f,S as R,i as s}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const S="52299901-ed5308505488786f07030921d";f.defaults.baseURL="https://pixabay.com/api/";const m=15;async function g(o,t=1){const{data:n}=await f.get("",{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:m}});return n}const h=document.querySelector(".gallery"),p=document.getElementById("loader"),y=document.getElementById("load-more"),M=new R(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(({webformatURL:n,largeImageURL:l,tags:e,likes:r,views:i,comments:E,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy"/>
        </a>
        <div class="card-meta">
          <span><b>Likes</b>${r}</span>
          <span><b>Views</b>${i}</span>
          <span><b>Comments</b>${E}</span>
          <span><b>Downloads</b>${P}</span>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){h.innerHTML=""}function b(){p.classList.add("show")}function w(){p.classList.remove("show")}function v(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}function q(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const B=document.getElementById("search-form"),I=document.getElementById("load-more");let c="",a=1,u=0;B.addEventListener("submit",A);I.addEventListener("click",O);async function A(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){s.warning({message:"Please enter a search query",position:"topRight"});return}a=1,$(),d(),b();try{const t=await g(c,a);if(u=t.totalHits||0,!t.hits||t.hits.length===0){s.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t.hits),a*m<u?v():(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{w(),B.reset()}}async function O(){a+=1,b(),d();try{const o=await g(c,a);L(o.hits),q(),a*m<u?v():(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Failed to load more images.",position:"topRight"})}finally{w()}}
//# sourceMappingURL=index.js.map
